export const MODIFY_PROFILE_REQUEST = 'MODIFY_PROFILE_REQUEST'
export const MODIFY_PROFILE_SUCCESS = 'MODIFY_PROFILE_SUCCESS'
export const MODIFY_PROFILE_FAILURE = 'MODIFY_PROFILE_FAILURE'

export const CHANGE_ACCOUNT_ACTIVITY_REQUEST = 'CHANGE_ACCOUNT_ACTIVITY_REQUEST'
export const CHANGE_ACCOUNT_ACTIVITY_SUCCESS = 'CHANGE_ACCOUNT_ACTIVITY_SUCCESS'

export const DELETE_ACCOUNT_REQUEST = 'DELETE_ACCOUNT_REQUEST'
export const DELETE_ACCOUNT_DATA_SUCCESS = 'DELETE_ACCOUNT_DATA_SUCCESS'
export const DELETE_ACCOUNT_DATA_FAILURE = 'DELETE_ACCOUNT_DATA_FAILURE'

export const FETCH_PREFERENCES_REQUEST = 'FETCH_PREFERENCES_REQUEST'
export const FETCH_PREFERENCES_SUCCESS = 'FETCH_PREFERENCES_SUCCESS'
export const FETCH_PREFERENCES_FAILURE = 'FETCH_PREFERENCES_FAILURE'

export const REMOVE_PREFERENCE_REQUEST = 'REMOVE_PREFERENCE_REQUEST'
export const REMOVE_PREFERENCE_SUCCESS = 'REMOVE_PREFERENCE_SUCCESS'
export const REMOVE_PREFERENCE_FAILURE = 'REMOVE_PREFERENCE_FAILURE'
